name: Build and Deploy Docs Site to Google Cloud Storage

on:
  push:
    branches:
      - feat-deploy-test
  workflow_dispatch:

env:
  GCP_BUCKET_NAME: ni-compute-doc-page
  ASTRO_BUILD_DIR: dist/
  PROJECT_ID: ni-sn27-frontend-prod
  PROJECT_NUMBER: 411140518733
  PROJECT_SHORT: prod

jobs:
  deploy:
    name: Deploy to Cloud Storage
    runs-on: ubuntu-latest
    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and Cache Dependencies
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install Dependencies
        run: npm ci

      - name: Build Astro Project
        run: npm run build

      - name: Authenticate to Google Cloud
        id: auth
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/${{ env.PROJECT_NUMBER }}/locations/global/workloadIdentityPools/github-wlid-pool/providers/github-wlid-pool-provider
          service_account: github-actions@ni-sn27-frontend-${{ env.PROJECT_SHORT }}.iam.gserviceaccount.com

      - name: GCP Setup | Install and Configure Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Deploy to Google Cloud Storage
        run: |-
          gcloud storage rsync ${{ env.ASTRO_BUILD_DIR }} gs://${{ env.GCP_BUCKET_NAME }} --recursive --delete-unmatched-destination-objects --checksum

      - name: Deployment successful!
        run: echo "Site successfully deployed to gs://${{ env.GCP_BUCKET_NAME }}"
